# Generated by Django 6.0.7 on 2026-07-13 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='sos_user3',
        ),
    ]
